# Generated by Django 4.1.3 on 2023-01-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolUic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('card_indentification', models.IntegerField()),
                ('date_of_bird', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('cellphone', models.IntegerField()),
                ('gender', models.CharField(max_length=60)),
                ('civil_status', models.CharField(max_length=60)),
                ('ethnicity', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('career', models.CharField(max_length=60)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.roluic')),
            ],
        ),
    ]
